from datetime import datetime
from getResponse import get_report
from fpdf import FPDF
from PIL import Image
import os, time, random

class PDF(FPDF):
    def header(self):
        # Logo (adjust path and dimensions as needed)
        logo_path = "logo.jpg"  # Make sure this file exists in your directory
        if os.path.exists(logo_path):
            self.image(logo_path, x=10, y=8, w=14)  # ⬅️ smaller logo

        # Title next to the logo
        self.set_font('Arial', 'B', 22)
        self.set_xy(35, 10)  # Move to the right of the logo
        self.cell(0, 10, 'Wafer Analysis by WaferGPT', ln=True, align='L')
        self.ln(15)


    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 10)
        self.set_text_color(169, 169, 169)
        self.cell(0, 10, 'Generated by WaferGPT', align='C')

    def add_section(self, title, text, image_path=None):
        self.set_font("Arial", 'B', 13)
        self.set_text_color(0)
        self.cell(0, 10, title, ln=True)
        self.set_font("Arial", '', 12)
        self.multi_cell(0, 10, text)
        self.ln(3)

        if image_path and os.path.exists(image_path):
            # Resize to fit within page margins (e.g., 150mm width max)
            max_width = 50  # in mm
            self.image(image_path, w=max_width)
            self.ln(5)

    def watermark(self):
        self.set_text_color(220, 220, 220)
        self.set_font('Arial', 'B', 50)  # Bigger font
        self.rotate(45, x=self.w / 2, y=self.h / 2)  # Rotate around center
        self.text(x=30, y=self.h / 2, txt='WaferGPT')  # Draw across the page
        self._out('Q')  # Reset rotation

    def rotate(self, angle, x=None, y=None):
        from math import cos, sin, pi
        if x is None: x = self.x
        if y is None: y = self.y
        angle_rad = angle * pi / 180
        c = cos(angle_rad)
        s = sin(angle_rad)
        cx = x * self.k
        cy = (self.h - y) * self.k
        self._out(f'q {c:.5f} {s:.5f} {-s:.5f} {c:.5f} {cx:.2f} {cy:.2f} cm')


ROOT_CAUSES = [
    "Contamination during the photolithography process.",
    "Irregularities in the chemical etching stage.",
    "Microscopic particle deposits on the wafer surface.",
    "Tool misalignment in the etching chamber.",
    "Temperature instability during ion implantation."
]

def generate_pdf_report(image_path):
    pdf = PDF()
    pdf.add_page()
    api_result = get_report(image_path)  # Call the API to get the report data
    # Section 1: Defect Description
    classification = api_result.get("classification", "N/A")
    pdf.add_section("1. Defect Summary", f"{classification}", image_path)

    root_cause = random.choice(ROOT_CAUSES)
    pdf.add_section("2. Root Cause Analysis", f"Probable cause of this defect: {root_cause}")

    # Section 2: Defect Location
    loc = api_result.get("localization", {})
    loc_text = loc.get("value", "N/A")
    loc_img = loc.get("image_path", None)
    pdf.add_section("3. Detected Defect Location", f"{loc_text}", loc_img)

    # Section 3: Defect Quantification
    quant = api_result.get("defect_percentage", {})
    quant_text = quant.get("value", "N/A")
    quant_img = quant.get("image_path", None)
    pdf.add_section("4. Defect Quantification", f"{quant_text}", quant_img)

    # Save to file

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = f"reports/wafer_report_{timestamp}.pdf"

    pdf.output(report_path)
    time.sleep(3)
    return os.path.abspath(report_path)  # ✅ Return absolute path
    # time.sleep(10)

if __name__ == "__main__":
    # Example usage
    image_path = 'png_files/image1.png'  #
    report_path = generate_pdf_report(image_path)
    print(f"Report generated at: {report_path}")

