from typing import List, Optional, TypedDict, Tuple, Dict, Any
from pydantic import BaseModel, Field

# --- Pydantic Models for each Agent's structured output ---


class DefectLocation(BaseModel):
    """Detailed information about a single localized defect."""
    bounding_box: Tuple[int, int, int, int] = Field(description="(x_min, y_min, x_max, y_max) coordinates of the defect")
    center_point: Tuple[int, int] = Field(description="(x, y) center coordinate of the defect")
    description: str = Field(description="Textual description of the defect's location, e.g., 'top-left quadrant'")
    is_largest: bool = Field(default=False, description="Indicates if this is the largest detected defect")


class LocalizationData(BaseModel):
    """The structured output from the DefectLocalizer agent."""
    defects_found: str = Field(description="Textual description of the defect's location, e.g., 'top-left quadrant'")
    output_image_path: Optional[str] = Field(default=None, description="Path to the image with defects visualized")


class PercentageData(BaseModel):
    """The structured output from the DefectPercentageCalculator agent."""
    defect_percentage: str = Field(description="The percentage of the wafer that is defective")
    output_image_path: Optional[str] = Field(default=None, description="Path to the image with defects visualized")


class ClassificationData(BaseModel):
    """The structured output from the DefectClassifier agent."""
    defect_type: str = Field(description="The classified type of the defect, e.g., 'Scratch', 'Contamination'")
    confidence_score: Optional[float] = Field(default=None, description="The model's confidence in the classification")


class GeneralAnalysisData(BaseModel):
    """The structured output from the MultimodalLLMTool (generalist) agent."""
    summary: str = Field(description="A general textual summary or answer based on the image")

class SQLAnalysisData(BaseModel):
    """The structured output from the SQL Agent."""
    query: str = Field(description="The SQL query generated by the agent")
    data_points: List[Dict[str, Any]] = Field(description="The raw data rows returned from the database")
    summary: str = Field(description="A brief natural language summary of the data")



class AgentState(TypedDict, total=False):
    """
    State passed between agents in the semiconductor analysis workflow.
    """
    # --- Inputs ---
    question: str
    image_path: str

    # --- Agent Outputs (Structured Data) ---
    percentage_data: Optional[PercentageData]
    localization_data: Optional[LocalizationData]
    classification_data: Optional[ClassificationData]
    general_analysis_data: Optional[GeneralAnalysisData]
    sql_data: Optional[SQLAnalysisData] 


    # --- Workflow Management ---
    required_agents: List[str] # List of agents needed to answer the query
    completed_agents: List[str] # List of agents that have already run
    current_agent: str # The agent currently being executed

    # --- Final Output & Errors ---
    response: Optional[str] # The final, user-facing response string
    error: Optional[str] # To store any errors that occur